name: Attach Debug APKs To Release

on:
  release:
    types:
      - published

jobs:
  attach-apks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Build and attach APKs to release
        shell: bash {0}
        run: |
          exit_on_error() {
              echo "$1"
              echo "Deleting '$RELEASE_VERSION_NAME' release and '$GITHUB_REF' tag"
              hub release delete "$RELEASE_VERSION_NAME"
              git push --delete origin "$GITHUB_REF"
              exit 1
          }

          echo "Setting vars"
          RELEASE_VERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          APK_DIR_PATH="./app/build/outputs/apk/debug"
          APK_VERSION_TAG="$RELEASE_VERSION_NAME-github-debug"
          APK_BASENAME_PREFIX="termux-styling_$APK_VERSION_TAG"

          echo "Building APKs for 'APK_VERSION_TAG' release"
          if ! ./gradlew assembleDebug; then
            exit_on_error "Build failed for '$APK_VERSION_TAG' release."
          fi

          echo "Renaming app-debug.apk to release name"
          if ! (mv ${APK_DIR_PATH}/app-debug.apk ${APK_DIR_PATH}/${APK_BASENAME_PREFIX}.apk); then
            exit_on_error "Failed to rename '$APK_VERSION_TAG' release apk filename."
          fi

          echo "Generating sha25sums file"
          if ! (cd "$APK_DIR_PATH"; sha256sum \
            "${APK_BASENAME_PREFIX}.apk" \
            > "${APK_BASENAME_PREFIX}_sha256sum"); then
            exit_on_error "Generate sha25sums failed for '$APK_VERSION_TAG' release."
          fi

          echo "Attaching APKs to github release"
          if ! hub release edit \
          -m "" \
          -a "$APK_DIR_PATH/${APK_BASENAME_PREFIX}.apk" \
          -a "$APK_DIR_PATH/${APK_BASENAME_PREFIX}_sha256sum" \
          "$RELEASE_VERSION_NAME"; then
            exit_on_error "Attach APKs to release failed for '$APK_VERSION_TAG' release."
          fi
